### ISSUE TITLE
マッチング処理

### ISSUE THREAD

**Issue by KOU050223** [jyogi-web/ankylo-monorepo#9]

**Comment by KOU050223** [comment]
1. ユーザー登録と認証
2. ルームの作成
目的: ユーザーが対戦するためのゲームルームを作成する。

関与するテーブル:

rooms
room_members
データの動き:

ルーム作成時:

ユーザーがルーム名を指定してルームを作成。
rooms テーブルに新しいルームレコードを挿入。
作成者を room_members テーブルにリーダーとして追加。
3. ルームへの参加
目的: 他のユーザーが既存のルームに参加し、対戦相手を見つける。

関与するテーブル:

rooms
room_members
データの動き:

ルームへの参加時:

ユーザーがルームIDを指定して参加をリクエスト。
room_members テーブルに新しいレコードを追加。ただし、同一ユーザーが同じルームに複数回参加しないようにユニーク制約が適用されています。
ルームの状態更新（オプション）:

参加人数が満員になる（例えば、2人対戦の場合）と、rooms テーブルの status を 'in_game' に更新。
4. マッチの開始
目的: ルーム内の参加者間で実際の対戦を開始する。

関与するテーブル:

matches
decks
deck_cards
データの動き:

マッチの作成:

ルームの status が 'in_game' になったタイミングで、matches テーブルに新しいマッチレコードを作成。
対戦に使用するデッキを指定（ここでは固定デッキと仮定）。
注意点:

player1_id と player2_id はルーム内の参加者を指します。
deck_id は事前に用意されたデッキのIDを指定します。
5. マッチの進行と結果の保存
目的: 対戦中のゲームロジックに従って、カードのプレイやターンの進行を管理し、結果を保存する。

関与するテーブル:

matches
その他必要に応じて、追加のテーブル（例: match_logs）を使用
データの動き:

ゲームプレイ中:

各プレイヤーがターンごとにカードをプレイ。
ゲームの進行状況（例: 現在のターン、プレイヤーのライフポイントなど）は matches テーブルの current_turn や他のカラムで管理。
詳細なゲームログを保存する場合、match_logs などの追加テーブルを使用して、各アクションを記録します。
マッチの終了:

勝者が決定した時点で、matches テーブルの end_time と result を更新。
6. マッチ後の処理
目的: マッチ結果を基にユーザーのステータスを更新したり、統計情報を保存したりする。

関与するテーブル:

matches
その他必要に応じて、追加のテーブル（例: user_stats）
データの動き:

ユーザーのステータス更新（例: 勝利数の増加）:

user_stats テーブルが存在する場合、該当ユーザーの統計情報を更新。
ルームの状態更新:

マッチ終了後、rooms テーブルの status を 'closed' に変更。
データの流れを視覚化
以下に、各テーブル間の関係とマッチング処理時のデータの流れを図式的に示します。

[Users] <-- created_by -- [Rooms] <-- room_id -- [RoomMembers] --> user_id -- [Users]
                 |
                 |-- [Matches] <-- player1_id -- [Users]
                 |          |          <-- player2_id -- [Users]
                 |          |          <-- deck_id -- [Decks] <-- owner_id -- [Users]
                 |
                 |-- [DeckCards] --> card_id -- [Cards]
各テーブル間のリレーションシップ
UsersとRooms:

ユーザーは複数のルームを作成（1対多）
ルームは1人のユーザーによって作成（多対1）
RoomsとRoomMembers:

ルームには複数のメンバーが参加（1対多）
メンバーは1つのルームに所属（多対1）
UsersとRoomMembers:

ユーザーは複数のルームに参加可能（1対多）
RoomMemberは1人のユーザーに属する（多対1）
MatchesとRooms:

ルームには複数のマッチが関連（1対多）
マッチは1つのルームに属する（多対1）
MatchesとUsers:

マッチには2人のプレイヤーが参加（player1とplayer2、両方とも多対1）
MatchesとDecks:

マッチは1つのデッキを使用（多対1）
デッキは複数のマッチで使用可能（1対多）
DecksとDeckCards:

デッキには複数のカードが含まれる（1対多）
DeckCardは1つのデッキに属する（多対1）
DeckCardsとCards:

DeckCardは1つのカードに属する（多対1）
カードは複数のデッキに含まれる（1対多）

**Comment by Yanai1005** [comment]
ルーム作成・入室はできたので一旦Close
